### ISSUE TITLE
run on docker

### ISSUE THREAD

**Issue by twocolors** [CANDY-LINE/node-red-contrib-generic-ble#45]
hi, plz help how use this node in "docker nodered/node-red:latest-minimal"

```
23 Jan 20:57:05 - [error] [GenericBLE:ERROR] The name org.bluez was not provided by any .service files, DBusError: The name org.bluez was not provided by any .service files,
    at _methodReturnHandlers.(anonymous function) (/data/node_modules/dbus-next/lib/bus.js:339:27),
    at handleMessage (/data/node_modules/dbus-next/lib/bus.js:98:11),
    at EventEmitter.MessageBus.conn.on (/data/node_modules/dbus-next/lib/bus.js:147:9),
    at EventEmitter.emit (events.js:198:13),
    at /data/node_modules/dbus-next/lib/connection.js:112:14,
    at Socket.<anonymous> (/data/node_modules/dbus-next/lib/message.js:63:9),
    at Socket.emit (events.js:198:13),
    at emitReadable_ (_stream_readable.js:555:12),
    at process._tickCallback (internal/process/next_tick.js:63:19),
```

node-red run from user 'node-red' in Alpine Linux

**Comment by twocolors** [comment]
maybe add use docker 'hci socket' ?

**Comment by twocolors** [comment]
@dbaba can you help ?

**Comment by dbaba** [comment]
The error says Bluetoothd is not running on your container.
Unfortunately, I don't have any idea of the way to running Bluetoothd on Docker since I haven't tried it.
Please ask it in a more appropriate place such as Docker forums.

**Comment by twocolors** [comment]
Thanks, the Bluetooth implementation only works in debian based containers, officially build a docker on alpine (https://github.com/node-red/node-red-docker/blob/master/.docker/Dockerfile.alpine)

Have you thought about doing a check if dbus is not available, use '@abandonware/noble' ?

**Comment by twocolors** [comment]
thanks for the direction to solve the problem, if you need to use a container (docker), then you need to take the host **dbus**

```
  node-red:
    image: nodered/node-red:latest-minimal
    container_name: node-red
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - UDEV=1
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/pi/.node-red:/data
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
    restart: unless-stopped

```
